entity file generated and user signup endpoint created
Zummit-Africa-Inc/zapi-dummy-identity pull request #2
Opened 2022-05-20 09:39 UTC by SunmadeBabafemi

@PhilemonBrain @Chimexx Please Review for merging
thanks

2022-05-22 18:55 UTC, Chimexx requested changes

2022-05-22 18:55 UTC, Chimexx commented on src/auth/auth.controller.ts
> +        return user
What happened to the custom response object?, confirm if you are to use it.

2022-05-22 18:55 UTC, Chimexx commented on src/auth/dto/update-user.dto.ts
> +    @IsOptional()
Are you supposed to make email and pwd fields optional?

2022-05-22 18:55 UTC, Chimexx commented on src/entities/user.entity.ts
> +// export class HashPassword{
Remove commented codes that you won't  use in the future

2022-05-22 18:55 UTC, Chimexx commented on src/user/user.service.ts
> +            return null
Return a more descriptive result, null gives no information.

2022-05-22 18:55 UTC, Chimexx commented on src/user/user.service.ts
> +        return await  this.usersrepo.findOne({where:{email: email}})
What if the user wasn't found? or incorrect email was supplied?

2022-05-22 18:55 UTC, Chimexx commented on src/user/user.controller.ts
> +export class UserController {}
Why is the controller incomplete?

2022-05-23 09:03 UTC, SunmadeBabafemi commented on src/auth/dto/update-user.dto.ts
> +    @IsOptional()
yes if a user is to be updated it could be other fields that need updating... its optional to update the email and password with every update

2022-05-23 09:04 UTC, SunmadeBabafemi commented on src/auth/auth.controller.ts
> +        return user
that has just been fixed but for some reason its not returning the custom response object

2022-05-23 09:12 UTC, Chimexx commented on src/auth/dto/update-user.dto.ts
> +    @IsOptional()
Okay, well I didn't see any update function in the service, so I cant tell if you are querying the user via id or email, email can't be optional if you are querying with email.

2022-05-23 09:34 UTC, SunmadeBabafemi commented on src/user/user.service.ts
> +            return null
a custom response object is now being used instead

2022-05-23 09:37 UTC, SunmadeBabafemi commented on src/user/user.service.ts
> +        return await  this.usersrepo.findOne({where:{email: email}})
a custom response object is now being used instead

2022-05-23 09:37 UTC, SunmadeBabafemi commented on src/user/user.controller.ts
> +export class UserController {}
the auth controller is used instead

2022-05-23 09:54 UTC, SunmadeBabafemi reviewed
@PhilemonBrain @Chimexx changes made based on last review by @Chimexx ...

2022-05-23 10:40 UTC, Chimexx commented on src/user/user.service.ts
> +        return await  this.usersrepo.findOne({where:{email: email}})
Good

2022-05-23 10:56 UTC, Chimexx commented on src/user/user.controller.ts
> +export class UserController {}
Okay

2022-05-23 10:56 UTC, Chimexx commented on src/user/user.service.ts
> +            return null
Good

2022-05-23 11:08 UTC, Chimexx commented on src/user/user.service.ts
>  }
async findByEmail(email: string){
const user=  await  this.usersrepo.findOne({where:{email: email}})
if (!user) {
      throw new NotFoundException(
        ZuAppResponse.NotFoundRequest('Not Found', 'User does not exist'),
      );
    }
    return user;
}

Compare and adjust

2022-05-23 11:11 UTC, SunmadeBabafemi commented on src/user/user.service.ts
>  }
yes sir.. changes made in the new PR

2022-05-23 11:12 UTC, Chimexx commented on src/user/user.service.ts
>  }
Okay

2022-05-23 11:25 UTC, closed without merging