Verify & create user profile
Zummit-Africa-Inc/zapi-dummy-identity pull request #22
Opened 2022-07-13 10:45 UTC by Jude-adesulu

The work flow
- A verification link(containing a token) will be sent to user at the time of acc creation
- Once the mail link is clicked by the user, an endpoint is waiting to consume the token and verify
- Upon verification, a call to axios request for a profile to be created to user
- The profile is then returned to the user
- Also verification is resend to a user on account recreating if mail wasn't confirmed the first time

WARNING!!! I'm yet to generate a migration file, do well and generate before use

2022-07-14 13:15 UTC, PhilemonBrain requested changes

2022-07-14 13:15 UTC, PhilemonBrain commented on .env.example
> +NOTIFICATION_URL=NOTIFICATION_BASE_URL/email/send-mail
the NOTIFICATION_URL should be the base url only. the extra part which is the route should be in ur code please

2022-07-14 13:15 UTC, PhilemonBrain commented on src/common/constants/config.constant.ts
> +  baseUrl: {
this might be better as baseUrl.notification not baseUrl.notificationUrl

2022-07-14 13:57 UTC, Jude-adesulu commented on .env.example
> +NOTIFICATION_URL=NOTIFICATION_BASE_URL/email/send-mail
Okay noted.  I'm on it

2022-07-14 13:57 UTC, Chimexx requested changes

2022-07-14 13:57 UTC, Chimexx commented on src/email-verification/email-verification.controller.ts
> +      emailTokenDto.token,
Pass this into a custom return object, check other controller files

2022-07-14 13:57 UTC, Chimexx commented on src/email-verification/email-verification.service.ts
> +    const payload: VerifyToken = { email };
Is payload neccessary? just use email

2022-07-14 14:00 UTC, Jude-adesulu commented on src/email-verification/email-verification.service.ts
> +    const payload: VerifyToken = { email };
I was having some errors when I passed it directly, that's why I used this method.  I will see if I can get it changed

2022-07-14 14:57 UTC, Jude-adesulu commented on src/email-verification/email-verification.controller.ts
> +      emailTokenDto.token,
> 

I just checked auth controller I didn't see any customer respone for it

2022-07-14 20:59 UTC, PhilemonBrain requested changes

2022-07-14 20:59 UTC, PhilemonBrain commented on src/email-verification/email-verification.controller.ts
> +      emailTokenDto.token,
@Jude-adesulu if you check the dummy-core service, you'll see that we wrap the resposnse from the service methods in a ZAResponse.Ok object like this : 

const example = await this.emailVerificatioService.decodeEmailToken(
      emailTokenDto.token)
return ZapiResponse.Ok(example, 'Ok', '200')

2022-07-14 20:59 UTC, PhilemonBrain commented on src/email-verification/email-verification.service.ts
> +    const payload: VerifyToken = { email };
@Jude-adesulu its okay this way if it works.

2022-07-15 06:12 UTC, PhilemonBrain approved these changes

2022-07-15 06:12 UTC, merged