Change password
Zummit-Africa-Inc/zapi-dummy-identity pull request #25
Opened 2022-07-17 17:52 UTC by alahirajeffrey

Created route to change user password while the user is logged in

2022-07-18 09:19 UTC, andyjrII requested changes
While the endpoint works, but I have some suggestions:

1. There should be a verification that the user who is logged in is actually the person trying to change the password, so there should be a confirmation of password before the new one can be accepted and changed.
2.  There is no response that the password has successfully been changed.

2022-07-18 18:59 UTC, andyjrII commented
Works now but you haven't addressed the responses your endpoint gives. if the old password is wrong, or the new password and confirm password doesnt match or follows wrong format, it just returns 400, it doesn't tell us what was wrong,

Also when it is successful, it isnt telling us whether it is successful or not, just returns a 200

2022-07-19 06:23 UTC, PhilemonBrain commented
@andyjrII thanks for your detailed review of this PR

2022-07-19 08:33 UTC, andyjrII approved these changes

2022-07-20 13:07 UTC, PhilemonBrain requested changes

2022-07-20 13:07 UTC, PhilemonBrain commented on src/auth/auth.service.ts
> +  async changePassword(dto: ChangePasswordDto ){
@alahirajeffrey what are you using the access tokoen for

2022-07-20 13:07 UTC, PhilemonBrain commented on src/user/dto/change-password.dto.ts
> +    accessToken: string
@alahirajeffrey i dont know what this token is for

2022-07-20 13:07 UTC, PhilemonBrain commented on src/user/dto/change-password.dto.ts
> +    newPassword: string;
what is this passwordConfirm for

2022-07-20 13:07 UTC, PhilemonBrain commented on src/auth/auth.service.ts
> +    if(!payload){
when this token is decoded, what is expected to be in the payload

2022-07-20 14:39 UTC, Chimexx requested changes
Basically changing password happens in these steps
- unhash the saved password 
- compare it with the old inputed password 
- if they match, hash the new password and save it.

A lot of things you did here are unneccesary

2022-07-20 14:39 UTC, Chimexx commented on src/auth/auth.service.ts
> +    const payload = await this.jwtTokenService.verify(dto.accessToken, {secret: await this.configService.get(jwtConstants.access_secret)})
Do you need jwt to change password as a logged in user?

2022-07-20 14:39 UTC, Chimexx commented on src/auth/auth.service.ts
> +      throw new BadRequestException(
Good

2022-07-20 14:39 UTC, Chimexx commented on src/user/dto/change-password.dto.ts
> +    @IsNotEmpty({message: 'Please input your signin access token'})
Token? Use yourself as an example, how may sites or apps has ever asked you for a token when changing password as a logged in user?

2022-07-20 14:39 UTC, Chimexx commented on src/user/dto/change-password.dto.ts
> +    newPasswordConfirm: string;
All these validators in the dto, are they neccessary?

2022-07-20 16:00 UTC, alahirajeffrey commented on src/auth/auth.service.ts
> +  async changePassword(dto: ChangePasswordDto ){
When a user logs in, an access and refresh token is sent to the user to access protected routes. The access token there is meant to verify the user

2022-07-20 16:00 UTC, alahirajeffrey commented on src/user/dto/change-password.dto.ts
> +    accessToken: string
It's the token which would be verified to check if the user has access to the token

2022-07-20 16:03 UTC, alahirajeffrey commented on src/auth/auth.service.ts
> +    if(!payload){
The Payload there is supposed to provide the user's details such as ID so I can check the password in the database to see if it matches with what the user would provide in the change password dto

2022-07-20 16:04 UTC, alahirajeffrey commented on src/user/dto/change-password.dto.ts
> +    @IsNotEmpty({message: 'Please input your signin access token'})
That is supposed to be a message for the frontend guys in case they come across errorrs

2022-07-20 16:04 UTC, alahirajeffrey commented on src/auth/auth.service.ts
> +      throw new BadRequestException(
Thanks

2022-07-20 16:05 UTC, alahirajeffrey commented on src/auth/auth.service.ts
> +    const payload = await this.jwtTokenService.verify(dto.accessToken, {secret: await this.configService.get(jwtConstants.access_secret)})
I was just trying to verify if the user had access to change password

2022-07-20 19:09 UTC, alahirajeffrey commented on src/user/dto/change-password.dto.ts
> +    newPasswordConfirm: string;
Alright. I'll get rid of them

2022-07-21 12:23 UTC, DorcasOJ commented on src/user/dto/change-password.dto.ts
> +    @IsNotEmpty({message: 'Please input your signin access token'})
Maybe you can inform the frontend guy instead of putting it there

2022-07-21 12:26 UTC, DorcasOJ approved these changes
Good, though I wasn't able to test it.

2022-07-21 19:11 UTC, Chimexx requested changes

2022-07-21 19:11 UTC, Chimexx commented on src/auth/auth.service.ts
>      const currentPasswordHash = user.password
What exactly are you doing here? You are supposed to unhash the saved password to enable you compare

2022-07-21 19:11 UTC, Chimexx commented on src/auth/auth.service.ts
>      const oldPasswordHash = await this.jwtHelperService.hashPassword(dto.oldPassword, user.password.split(':')[0] )
Jwt is used to encode and decode, not to hash password, find out the library used in hashing the password in package.json. Use it to do your hashing.

You can research the difference between jwt and hashing libraries like Bcrypt and argon

2022-07-21 19:24 UTC, Chimexx commented on src/auth/auth.service.ts
>      const currentPasswordHash = user.password
1. Get the password from the db and unhash it.
2. compare the unhashed saved password with the current inputed password. (Comparing two unhashed strings)
3. If they match, hash the new password and save it.

2022-07-22 07:30 UTC, PhilemonBrain commented on src/auth/auth.service.ts
> +  async changePassword(dto: ChangePasswordDto ){
@alahirajeffrey i think it makes sense. remind during the standup to address it. We will implement it but with a different logic

2022-07-22 08:23 UTC, alahirajeffrey commented on src/auth/auth.service.ts
>      const currentPasswordHash = user.password
The passwords are hashed using the pbkdf2Sync function. From what I have seen online, there really isn't a way for me to unhash the password and even if there was, its really not advisable. If you know a way I can do it though, Please let me know.

2022-07-25 10:23 UTC, PhilemonBrain approved these changes

2022-07-25 15:03 UTC, closed without merging