Login history feature
Zummit-Africa-Inc/zapi-dummy-identity pull request #35
Opened 2022-07-28 15:11 UTC by johnayinde

completed the login history feature @PhilemonBrain 

-user browser information such as OS name, time of making the request, browser name, IP address and country is sent along with the login credentials

-the info is saved in a list for every subsequent login request and returned in the response

2022-07-30 04:33 UTC, Jude-adesulu requested changes

2022-07-30 04:33 UTC, Jude-adesulu commented on src/common/interface/userInfo.interface.ts
> +export class UserInfo {
Use class-validator on these properties, some like @IsString()

2022-07-30 04:33 UTC, Jude-adesulu commented on src/user/user.controller.ts
> +import { UserInfo } from './../common/interface/userInfo.interface';
You are exporting a class right? Why is the name covention users.interface. you can use a dto as the extension name instead

2022-07-30 04:33 UTC, Jude-adesulu commented on src/user/user.controller.ts
> +    isArray: true,
Are you returning an array or an object? Cause the response in your service is an object type

2022-07-30 04:42 UTC, Jude-adesulu requested changes

2022-07-30 04:42 UTC, Jude-adesulu commented on src/user/user.service.ts
> +  }
Use the ZuAppResponse custom response here

2022-07-30 10:35 UTC, SunmadeBabafemi approved these changes
I believe it is now left for the frontend to fetch those data each time a user logs in right?....

nice work

2022-07-31 19:25 UTC, andyjrII approved these changes

2022-07-31 20:37 UTC, Jude-adesulu approved these changes
Good job bro

2022-07-31 20:37 UTC, johnayinde commented on src/user/user.controller.ts
> +import { UserInfo } from './../common/interface/userInfo.interface';
Changes made All fixed

2022-07-31 20:39 UTC, johnayinde commented
> Good job bro

2022-08-01 15:06 UTC, johnayinde commented
@PhilemonBrain

2022-08-02 08:43 UTC, PhilemonBrain approved these changes

2022-08-02 08:43 UTC, merged