Onetime reset link
Zummit-Africa-Inc/zapi-dummy-identity pull request #36
Opened 2022-08-03 06:28 UTC by johnayinde

-before reset link is sent a token is generated temporarily for a short expiration time
-when reset link is sent to the mail user is queried and check if token exist 
-and if the token expired user error message is sent to request for another reset link

- a user with a valid token can only reset password

2022-08-03 23:12 UTC, olawaley8 requested changes

2022-08-03 23:12 UTC, Jude-adesulu commented on src/auth/jwtHelper.service.ts
> +      expiresIn: await this.configService.get(jwtConstants.reset_time),
The jwtconstant for expiresIn should be access_time instead of reset_time

2022-08-04 09:11 UTC, johnayinde commented on src/auth/jwtHelper.service.ts
> +      expiresIn: await this.configService.get(jwtConstants.reset_time),
i created a new env variable for the reset it will have a shorter duration like 5m-10m 
if i should use the reset time s you said we'll endup have a user reusing a reset link multiple times

2022-08-05 08:48 UTC, PhilemonBrain approved these changes

2022-08-05 08:48 UTC, merged